### ISSUE TITLE
More racket analysis

### ISSUE THREAD

**Issue by dannypsnl** [aymanosman/intellij-racket#4]
https://github.com/aymanosman/intellij-racket/blob/master/src/main/kotlin/org/racket/ide/analysis/RacketAnalysis.kt I think we can use [annotations-mixin](https://docs.racket-lang.org/drracket-tools/Accessing_Check_Syntax_Programmatically.html#%28def._%28%28lib._drracket%2Fcheck-syntax..rkt%29._annotations-mixin%29%29) to get more helpful information

**Comment by aymanosman** [comment]
That's true. It could be added to one of the passes in https://github.com/aymanosman/racket-intellij.

The current implementation doesn't perform very well. It runs an external process to gather diagnostics on every code change. This, I think, is discouraged in the IntelliJ world. I think there are two alternatives.

1. Write all analyses in Kotlin/Java
2. Spawn a long running process to handle requests for updated diagnostics (basically [LSP](https://microsoft.github.io/language-server-protocol/))

Option 1 is not very attractive.

I'm not sure how to do options 2 since it doesn't appear to be an approach that the IntelliJ folks push very much.

I believe the Rust plugin goes mostly for option 1, and has to implement its own type inference (among other things)!

On the other hand, TypeScript support seems to rely on an external process (presumably LSP based).

General LSP support in IntelliJ is not good, last I checked.

**Comment by dannypsnl** [comment]
Option 1 will not work well with macros I believe. For option 2, LSP model is already developed for Racket, but I not sure the information they provided will fit intellij requirement.

I prefer provide customize process here, and I can work on this once we have analysis what to do here

**Comment by aymanosman** [comment]
Sounds good. I also think that that would be the best option to take.

For inspiration we can look at Greg Hendershott's excellent emacs package https://github.com/greghendershott/racket-mode.

**Comment by dannypsnl** [comment]
or https://github.com/racket-tw/sauron and https://github.com/jeapostrophe/racket-langserver, they all use the same way.
