### ISSUE TITLE
"Failed to invoke racket lint tool" 

### ISSUE THREAD

**Issue by rafaelm53539600** [aymanosman/intellij-racket#9]
Thank you for this interesting pluging. After installing, I got this popup message from Pycharm : "Failed to invoke racket lint tool" . Is there any environment PATH variable I have to fix?

 btw, I have already done "raco pkg install intellij"

**Comment by aymanosman** [comment]
What do you get when you do

```shell
> racket -lm intellij/lint-with-expand foo.rkt
```

This looks like you correctly have the path to the racket executable configured, but don't have the package installed (as far as the plugin can see).

**Comment by rafaelm53539600** [comment]
G:\>racket -v
Welcome to Racket v7.9 [bc].

G:\>echo '#lang racket badid' > foo.rkt

G:\>type foo.rkt
'#lang racket badid'

G:\>racket -lm intellij/lint-with-expand foo.rkt
0 "read failed"

**Comment by rafaelm53539600** [comment]
Can this help?

https://lists.racket-lang.org/users/archive/2011-January/043736.html

**Comment by aymanosman** [comment]
I found the problem. The plugin was **wrongly** claiming the package was not installed.

Fixed in this commit https://github.com/aymanosman/intellij-racket/commit/a751322a65e85ab6ddb756055b7e25393dd025f6.

This situation happens when the plugin get a non-zero exit code from invoking the racket lint tool, and tries to check if the tool in installed. The bug is the command-line to check if the package is installed had a typo :).

Another thing I'd like to do is improve the lint tool. It currently doesn't handle a file like this:

```shell
echo "#lang racketxxx" > foo.rkt
ayman@m1 /tmp> racket -lm intellij/lint-with-expand foo.rkt
standard-module-name-resolver: collection not found
  for module path: racketxxx/lang/reader
  collection: "racketxxx/lang"
  in collection directories:
   ...
```

I'd like it to return something like this instead

```
6 "collection not found" racketxxx
```

I'll keep this issue open until I've pushed out the next release.

**Comment by aymanosman** [comment]
I've pushed a new release https://github.com/aymanosman/intellij-racket/releases/tag/v0.0.14.

You can wait for JetBrains to approve the new verson or go to the release page install the plugin manually (if you know how) to test.

After this change, we won't get the erroneous notification anymore.

**Comment by rafaelm53539600** [comment]
I can confirm the patch is working . No longer popup alerts. Thanks !

**Comment by aymanosman** [comment]
I've also improved the linter so that the following works:

```shell
> echo "#lang racketxxx" > foo.rkt
> racket -lm intellij/lint-with-expand foo.rkt
0 "collection not found" racketxxx/lang/reader
```

So if you update the racket package, you will get better errors messages.
